language: python
python:
  - "3.9"


install:
  - pip install -r requirements.txt

script:
- black --check .
- flake8 --max-line-length=500 .
- coverage run manage.py test
- env

after_scripts:
- coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-106240719647
  on:
    repo: siddharthcv77/swe_app
    branch: main
  skip_cleanup: 'true'

# language: ruby
# rvm:
#  - 2.2
#  - jruby